name: Release Drafter

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
